# Generated by sonic-swss/bazel/generate.py. Do not edit.
# Source labels use the module's top-level component packages.

SWSS_PROGRAMS = {
    "buffermgrd": {
        "directory": "cfgmgr",
        "install_path": "usr/bin/buffermgrd",
        "local_include_directories": [
            "cfgmgr",
            ".",
            "lib",
            ".",
            "orchagent",
            "warmrestart",
            "orchagent/flex_counter"
        ],
        "sources": [
            "//cfgmgr:buffermgrd.cpp",
            "//cfgmgr:buffermgr.cpp",
            "//cfgmgr:buffermgrdyn.cpp",
            "//orchagent:orch.cpp",
            "//orchagent:request_parser.cpp",
            "//orchagent:response_publisher.cpp",
            "//lib:recorder.cpp"
        ]
    },
    "coppmgrd": {
        "directory": "cfgmgr",
        "install_path": "usr/bin/coppmgrd",
        "local_include_directories": [
            "cfgmgr",
            ".",
            "lib",
            ".",
            "orchagent",
            "warmrestart",
            "orchagent/flex_counter"
        ],
        "sources": [
            "//cfgmgr:coppmgrd.cpp",
            "//cfgmgr:coppmgr.cpp",
            "//orchagent:orch.cpp",
            "//orchagent:request_parser.cpp",
            "//orchagent:response_publisher.cpp",
            "//lib:recorder.cpp"
        ]
    },
    "fabricmgrd": {
        "directory": "cfgmgr",
        "install_path": "usr/bin/fabricmgrd",
        "local_include_directories": [
            "cfgmgr",
            ".",
            "lib",
            ".",
            "orchagent",
            "warmrestart",
            "orchagent/flex_counter"
        ],
        "sources": [
            "//cfgmgr:fabricmgrd.cpp",
            "//cfgmgr:fabricmgr.cpp",
            "//orchagent:orch.cpp",
            "//orchagent:request_parser.cpp",
            "//orchagent:response_publisher.cpp",
            "//lib:recorder.cpp"
        ]
    },
    "fdbsyncd": {
        "directory": "fdbsyncd",
        "install_path": "usr/bin/fdbsyncd",
        "local_include_directories": [
            "fdbsyncd",
            ".",
            ".",
            "warmrestart"
        ],
        "sources": [
            "//fdbsyncd:fdbsyncd.cpp",
            "//fdbsyncd:fdbsync.cpp",
            "//warmrestart:warmRestartAssist.cpp"
        ]
    },
    "fpmsyncd": {
        "directory": "fpmsyncd",
        "install_path": "usr/bin/fpmsyncd",
        "local_include_directories": [
            "fpmsyncd",
            ".",
            ".",
            "warmrestart",
            "fpmsyncd",
            "lib"
        ],
        "sources": [
            "//fpmsyncd:fpmsyncd.cpp",
            "//fpmsyncd:fpmlink.cpp",
            "//fpmsyncd:routesync.cpp",
            "//warmrestart:warmRestartHelper.cpp",
            "//lib:orch_zmq_config.cpp"
        ]
    },
    "gearsyncd": {
        "directory": "gearsyncd",
        "install_path": "usr/bin/gearsyncd",
        "local_include_directories": [
            "gearsyncd",
            ".",
            "lib",
            ".",
            "warmrestart",
            "cfgmgr"
        ],
        "sources": [
            "//lib:gearboxutils.cpp",
            "//gearsyncd:gearsyncd.cpp",
            "//gearsyncd:gearparserbase.cpp",
            "//gearsyncd:gearboxparser.cpp",
            "//gearsyncd:phyparser.cpp"
        ]
    },
    "intfmgrd": {
        "directory": "cfgmgr",
        "install_path": "usr/bin/intfmgrd",
        "local_include_directories": [
            "cfgmgr",
            ".",
            "lib",
            ".",
            "orchagent",
            "warmrestart",
            "orchagent/flex_counter"
        ],
        "sources": [
            "//cfgmgr:intfmgrd.cpp",
            "//cfgmgr:intfmgr.cpp",
            "//lib:subintf.cpp",
            "//orchagent:orch.cpp",
            "//orchagent:request_parser.cpp",
            "//orchagent:response_publisher.cpp",
            "//lib:recorder.cpp"
        ]
    },
    "macsecmgrd": {
        "directory": "cfgmgr",
        "install_path": "usr/bin/macsecmgrd",
        "local_include_directories": [
            "cfgmgr",
            ".",
            "lib",
            ".",
            "orchagent",
            "warmrestart",
            "orchagent/flex_counter"
        ],
        "sources": [
            "//cfgmgr:macsecmgrd.cpp",
            "//cfgmgr:macsecmgr.cpp",
            "//orchagent:orch.cpp",
            "//orchagent:request_parser.cpp",
            "//orchagent:response_publisher.cpp",
            "//lib:recorder.cpp",
            "//orchagent:macsecpost.cpp"
        ]
    },
    "mclagsyncd": {
        "directory": "mclagsyncd",
        "install_path": "usr/bin/mclagsyncd",
        "local_include_directories": [
            "mclagsyncd",
            ".",
            "."
        ],
        "sources": [
            "//mclagsyncd:mclagsyncd.cpp",
            "//mclagsyncd:mclaglink.cpp"
        ]
    },
    "natmgrd": {
        "directory": "cfgmgr",
        "install_path": "usr/bin/natmgrd",
        "local_include_directories": [
            "cfgmgr",
            ".",
            "lib",
            ".",
            "orchagent",
            "warmrestart",
            "orchagent/flex_counter"
        ],
        "sources": [
            "//cfgmgr:natmgrd.cpp",
            "//cfgmgr:natmgr.cpp",
            "//orchagent:orch.cpp",
            "//orchagent:request_parser.cpp",
            "//orchagent:response_publisher.cpp",
            "//lib:recorder.cpp"
        ]
    },
    "natsyncd": {
        "directory": "natsyncd",
        "install_path": "usr/bin/natsyncd",
        "local_include_directories": [
            "natsyncd",
            ".",
            ".",
            "warmrestart"
        ],
        "sources": [
            "//natsyncd:natsyncd.cpp",
            "//natsyncd:natsync.cpp",
            "//warmrestart:warmRestartAssist.cpp"
        ]
    },
    "nbrmgrd": {
        "directory": "cfgmgr",
        "install_path": "usr/bin/nbrmgrd",
        "local_include_directories": [
            "cfgmgr",
            ".",
            "lib",
            ".",
            "orchagent",
            "warmrestart",
            "orchagent/flex_counter"
        ],
        "sources": [
            "//cfgmgr:nbrmgrd.cpp",
            "//cfgmgr:nbrmgr.cpp",
            "//orchagent:orch.cpp",
            "//orchagent:request_parser.cpp",
            "//orchagent:response_publisher.cpp",
            "//lib:recorder.cpp"
        ]
    },
    "neighsyncd": {
        "directory": "neighsyncd",
        "install_path": "usr/bin/neighsyncd",
        "local_include_directories": [
            "neighsyncd",
            ".",
            ".",
            "warmrestart"
        ],
        "sources": [
            "//neighsyncd:neighsyncd.cpp",
            "//neighsyncd:neighsync.cpp",
            "//warmrestart:warmRestartAssist.cpp"
        ]
    },
    "orchagent": {
        "directory": "orchagent",
        "install_path": "usr/bin/orchagent",
        "local_include_directories": [
            "orchagent",
            ".",
            "lib",
            ".",
            "warmrestart",
            "orchagent/switch",
            "orchagent/flex_counter",
            "orchagent/debug_counter",
            "orchagent/port",
            "orchagent/pbh",
            "orchagent/nhg"
        ],
        "sources": [
            "//orchagent:main.cpp",
            "//lib:gearboxutils.cpp",
            "//lib:subintf.cpp",
            "//lib:recorder.cpp",
            "//lib:orch_zmq_config.cpp",
            "//orchagent:orchdaemon.cpp",
            "//orchagent:orch.cpp",
            "//orchagent:notifications.cpp",
            "//orchagent:nhgorch.cpp",
            "//orchagent:nhgbase.cpp",
            "//orchagent:cbf/cbfnhgorch.cpp",
            "//orchagent:cbf/nhgmaporch.cpp",
            "//orchagent:routeorch.cpp",
            "//orchagent:mplsrouteorch.cpp",
            "//orchagent:neighorch.cpp",
            "//orchagent:intfsorch.cpp",
            "//orchagent:evpnmhorch.cpp",
            "//orchagent:l2nhgorch.cpp",
            "//orchagent:port/port_capabilities.cpp",
            "//orchagent:port/porthlpr.cpp",
            "//orchagent:portsorch.cpp",
            "//orchagent:fabricportsorch.cpp",
            "//orchagent:fgnhgorch.cpp",
            "//orchagent:copporch.cpp",
            "//orchagent:tunneldecaporch.cpp",
            "//orchagent:qosorch.cpp",
            "//orchagent:buffer/bufferhelper.cpp",
            "//orchagent:bufferorch.cpp",
            "//orchagent:mirrororch.cpp",
            "//orchagent:fdborch.cpp",
            "//orchagent:macmoveguard.cpp",
            "//orchagent:aclorch.cpp",
            "//orchagent:pbh/pbhcap.cpp",
            "//orchagent:pbh/pbhcnt.cpp",
            "//orchagent:pbh/pbhmgr.cpp",
            "//orchagent:pbh/pbhrule.cpp",
            "//orchagent:pbhorch.cpp",
            "//orchagent:saihelper.cpp",
            "//orchagent:saiattr.cpp",
            "//orchagent:switch/switch_capabilities.cpp",
            "//orchagent:switch/switch_helper.cpp",
            "//orchagent:switch/trimming/capabilities.cpp",
            "//orchagent:switch/trimming/helper.cpp",
            "//orchagent:switchorch.cpp",
            "//orchagent:pfcwdorch.cpp",
            "//orchagent:pfcwdsworch.cpp",
            "//orchagent:pfcactionhandler.cpp",
            "//orchagent:crmorch.cpp",
            "//orchagent:request_parser.cpp",
            "//orchagent:vrforch.cpp",
            "//orchagent:countercheckorch.cpp",
            "//orchagent:vxlanorch.cpp",
            "//orchagent:tunneltermhelper.cpp",
            "//orchagent:vnetorch.cpp",
            "//orchagent:dtelorch.cpp",
            "//orchagent:flexcounterorch.cpp",
            "//orchagent:watermarkorch.cpp",
            "//orchagent:notificationconsumerstatsorch.cpp",
            "//orchagent:policerorch.cpp",
            "//orchagent:namelabelmapper.cpp",
            "//orchagent:sfloworch.cpp",
            "//orchagent:chassisorch.cpp",
            "//orchagent:debugcounterorch.cpp",
            "//orchagent:natorch.cpp",
            "//orchagent:mlagorch.cpp",
            "//orchagent:isolationgrouporch.cpp",
            "//orchagent:muxorch.cpp",
            "//orchagent:macsecorch.cpp",
            "//orchagent:lagid.cpp",
            "//orchagent:bfdorch.cpp",
            "//orchagent:icmporch.cpp",
            "//orchagent:srv6orch.cpp",
            "//orchagent:response_publisher.cpp",
            "//orchagent:nvgreorch.cpp",
            "//orchagent:zmqorch.cpp",
            "//orchagent:zmqrouteorch.cpp",
            "//orchagent:dash/dashenifwdorch.cpp",
            "//orchagent:dash/dashenifwdinfo.cpp",
            "//orchagent:dash/dashcounter.cpp",
            "//orchagent:dash/dashorch.cpp",
            "//orchagent:dash/dashrouteorch.cpp",
            "//orchagent:dash/dashvnetorch.cpp",
            "//orchagent:dash/dashaclorch.cpp",
            "//orchagent:dash/dashaclgroupmgr.cpp",
            "//orchagent:dash/dashmeterorch.cpp",
            "//orchagent:dash/dashtagmgr.cpp",
            "//orchagent:dash/dashtunnelorch.cpp",
            "//orchagent:dash/pbutils.cpp",
            "//orchagent:dash/dashhaorch.cpp",
            "//orchagent:dash/dashhafloworch.cpp",
            "//orchagent:dash/dashportmaporch.cpp",
            "//orchagent:dash/dashresulthelper.cpp",
            "//orchagent:twamporch.cpp",
            "//orchagent:stporch.cpp",
            "//orchagent:nexthopkey.cpp",
            "//orchagent:macsecpost.cpp",
            "//orchagent:high_frequency_telemetry/hftelorch.cpp",
            "//orchagent:high_frequency_telemetry/hftelprofile.cpp",
            "//orchagent:high_frequency_telemetry/counternameupdater.cpp",
            "//orchagent:high_frequency_telemetry/hftelutils.cpp",
            "//orchagent:high_frequency_telemetry/hftelgroup.cpp",
            "//orchagent:shlorch.cpp",
            "//orchagent:flex_counter/flex_counter_manager.cpp",
            "//orchagent:flex_counter/flex_counter_stat_manager.cpp",
            "//orchagent:flex_counter/flow_counter_handler.cpp",
            "//orchagent:flex_counter/flowcounterrouteorch.cpp",
            "//orchagent:debug_counter/debug_counter.cpp",
            "//orchagent:debug_counter/drop_counter.cpp",
            "//orchagent:p4orch/p4orch.cpp",
            "//orchagent:p4orch/p4orch_util.cpp",
            "//orchagent:p4orch/p4oidmapper.cpp",
            "//orchagent:p4orch/tables_definition_manager.cpp",
            "//orchagent:p4orch/router_interface_manager.cpp",
            "//orchagent:p4orch/gre_tunnel_manager.cpp",
            "//orchagent:p4orch/neighbor_manager.cpp",
            "//orchagent:p4orch/next_hop_manager.cpp",
            "//orchagent:p4orch/route_manager.cpp",
            "//orchagent:p4orch/acl_util.cpp",
            "//orchagent:p4orch/acl_table_manager.cpp",
            "//orchagent:p4orch/acl_rule_manager.cpp",
            "//orchagent:p4orch/wcmp_manager.cpp",
            "//orchagent:p4orch/mirror_session_manager.cpp",
            "//orchagent:p4orch/tunnel_decap_group_manager.cpp",
            "//orchagent:p4orch/l3_admit_manager.cpp",
            "//orchagent:p4orch/l3_multicast_manager.cpp",
            "//orchagent:p4orch/ip_multicast_manager.cpp",
            "//orchagent:p4orch/ext_tables_manager.cpp"
        ]
    },
    "orchagent_restart_check": {
        "directory": "orchagent",
        "install_path": "usr/bin/orchagent_restart_check",
        "local_include_directories": [
            "orchagent",
            ".",
            "lib",
            ".",
            "warmrestart",
            "orchagent/switch",
            "orchagent/flex_counter",
            "orchagent/debug_counter",
            "orchagent/port",
            "orchagent/pbh",
            "orchagent/nhg"
        ],
        "sources": [
            "//orchagent:orchagent_restart_check.cpp"
        ]
    },
    "portmgrd": {
        "directory": "cfgmgr",
        "install_path": "usr/bin/portmgrd",
        "local_include_directories": [
            "cfgmgr",
            ".",
            "lib",
            ".",
            "orchagent",
            "warmrestart",
            "orchagent/flex_counter"
        ],
        "sources": [
            "//cfgmgr:portmgrd.cpp",
            "//cfgmgr:portmgr.cpp",
            "//orchagent:orch.cpp",
            "//orchagent:request_parser.cpp",
            "//orchagent:response_publisher.cpp",
            "//lib:recorder.cpp"
        ]
    },
    "portsyncd": {
        "directory": "portsyncd",
        "install_path": "usr/bin/portsyncd",
        "local_include_directories": [
            "portsyncd",
            ".",
            "lib",
            ".",
            "warmrestart",
            "cfgmgr"
        ],
        "sources": [
            "//lib:gearboxutils.cpp",
            "//portsyncd:portsyncd.cpp",
            "//portsyncd:linksync.cpp"
        ]
    },
    "routeresync": {
        "directory": "orchagent",
        "install_path": "usr/bin/routeresync",
        "local_include_directories": [
            "orchagent",
            ".",
            "lib",
            ".",
            "warmrestart",
            "orchagent/switch",
            "orchagent/flex_counter",
            "orchagent/debug_counter",
            "orchagent/port",
            "orchagent/pbh",
            "orchagent/nhg"
        ],
        "sources": [
            "//orchagent:routeresync.cpp",
            "//lib:orch_zmq_config.cpp"
        ]
    },
    "sflowmgrd": {
        "directory": "cfgmgr",
        "install_path": "usr/bin/sflowmgrd",
        "local_include_directories": [
            "cfgmgr",
            ".",
            "lib",
            ".",
            "orchagent",
            "warmrestart",
            "orchagent/flex_counter"
        ],
        "sources": [
            "//cfgmgr:sflowmgrd.cpp",
            "//cfgmgr:sflowmgr.cpp",
            "//orchagent:orch.cpp",
            "//orchagent:request_parser.cpp",
            "//orchagent:response_publisher.cpp",
            "//lib:recorder.cpp"
        ]
    },
    "stpmgrd": {
        "directory": "cfgmgr",
        "install_path": "usr/bin/stpmgrd",
        "local_include_directories": [
            "cfgmgr",
            ".",
            "lib",
            ".",
            "orchagent",
            "warmrestart",
            "orchagent/flex_counter"
        ],
        "sources": [
            "//cfgmgr:stpmgrd.cpp",
            "//cfgmgr:stpmgr.cpp",
            "//orchagent:orch.cpp",
            "//orchagent:request_parser.cpp",
            "//orchagent:response_publisher.cpp",
            "//lib:recorder.cpp"
        ]
    },
    "swssconfig": {
        "directory": "swssconfig",
        "install_path": "usr/bin/swssconfig",
        "local_include_directories": [
            "swssconfig",
            ".",
            ".",
            "lib"
        ],
        "sources": [
            "//swssconfig:swssconfig.cpp",
            "//lib:orch_zmq_config.cpp"
        ]
    },
    "swssplayer": {
        "directory": "swssconfig",
        "install_path": "usr/bin/swssplayer",
        "local_include_directories": [
            "swssconfig",
            ".",
            ".",
            "lib"
        ],
        "sources": [
            "//swssconfig:swssplayer.cpp",
            "//lib:orch_zmq_config.cpp"
        ]
    },
    "teammgrd": {
        "directory": "cfgmgr",
        "install_path": "usr/bin/teammgrd",
        "local_include_directories": [
            "cfgmgr",
            ".",
            "lib",
            ".",
            "orchagent",
            "warmrestart",
            "orchagent/flex_counter"
        ],
        "sources": [
            "//cfgmgr:teammgrd.cpp",
            "//cfgmgr:teammgr.cpp",
            "//orchagent:orch.cpp",
            "//orchagent:request_parser.cpp",
            "//orchagent:response_publisher.cpp",
            "//lib:recorder.cpp"
        ]
    },
    "teamsyncd": {
        "directory": "teamsyncd",
        "install_path": "usr/bin/teamsyncd",
        "local_include_directories": [
            "teamsyncd",
            ".",
            "."
        ],
        "sources": [
            "//teamsyncd:teamsyncd.cpp",
            "//teamsyncd:teamsync.cpp"
        ]
    },
    "tlm_teamd": {
        "directory": "tlm_teamd",
        "install_path": "usr/bin/tlm_teamd",
        "local_include_directories": [
            "tlm_teamd",
            ".",
            ".",
            "lib"
        ],
        "sources": [
            "//tlm_teamd:main.cpp",
            "//tlm_teamd:teamdctl_mgr.cpp",
            "//tlm_teamd:values_store.cpp"
        ]
    },
    "tunnelmgrd": {
        "directory": "cfgmgr",
        "install_path": "usr/bin/tunnelmgrd",
        "local_include_directories": [
            "cfgmgr",
            ".",
            "lib",
            ".",
            "orchagent",
            "warmrestart",
            "orchagent/flex_counter"
        ],
        "sources": [
            "//cfgmgr:tunnelmgrd.cpp",
            "//cfgmgr:tunnelmgr.cpp",
            "//orchagent:orch.cpp",
            "//orchagent:request_parser.cpp",
            "//orchagent:response_publisher.cpp",
            "//lib:recorder.cpp"
        ]
    },
    "vlanmgrd": {
        "directory": "cfgmgr",
        "install_path": "usr/bin/vlanmgrd",
        "local_include_directories": [
            "cfgmgr",
            ".",
            "lib",
            ".",
            "orchagent",
            "warmrestart",
            "orchagent/flex_counter"
        ],
        "sources": [
            "//cfgmgr:vlanmgrd.cpp",
            "//cfgmgr:vlanmgr.cpp",
            "//orchagent:orch.cpp",
            "//orchagent:request_parser.cpp",
            "//orchagent:response_publisher.cpp",
            "//lib:recorder.cpp"
        ]
    },
    "vrfmgrd": {
        "directory": "cfgmgr",
        "install_path": "usr/bin/vrfmgrd",
        "local_include_directories": [
            "cfgmgr",
            ".",
            "lib",
            ".",
            "orchagent",
            "warmrestart",
            "orchagent/flex_counter"
        ],
        "sources": [
            "//cfgmgr:vrfmgrd.cpp",
            "//cfgmgr:vrfmgr.cpp",
            "//orchagent:orch.cpp",
            "//orchagent:request_parser.cpp",
            "//orchagent:response_publisher.cpp",
            "//lib:recorder.cpp"
        ]
    },
    "vxlanmgrd": {
        "directory": "cfgmgr",
        "install_path": "usr/bin/vxlanmgrd",
        "local_include_directories": [
            "cfgmgr",
            ".",
            "lib",
            ".",
            "orchagent",
            "warmrestart",
            "orchagent/flex_counter"
        ],
        "sources": [
            "//cfgmgr:vxlanmgrd.cpp",
            "//cfgmgr:vxlanmgr.cpp",
            "//orchagent:orch.cpp",
            "//orchagent:request_parser.cpp",
            "//orchagent:response_publisher.cpp",
            "//lib:recorder.cpp"
        ]
    }
}

SWSS_AUTOMAKE_INSTALL = [
    {
        "install_path": "usr/share/swss/buffer_check_headroom_barefoot.lua",
        "mode": 420,
        "source": "cfgmgr/buffer_check_headroom_barefoot.lua"
    },
    {
        "install_path": "usr/share/swss/buffer_check_headroom_mellanox.lua",
        "mode": 420,
        "source": "cfgmgr/buffer_check_headroom_mellanox.lua"
    },
    {
        "install_path": "usr/share/swss/buffer_check_headroom_vs.lua",
        "mode": 420,
        "source": "cfgmgr/buffer_check_headroom_mellanox.lua"
    },
    {
        "install_path": "usr/share/swss/buffer_headroom_barefoot.lua",
        "mode": 420,
        "source": "cfgmgr/buffer_headroom_barefoot.lua"
    },
    {
        "install_path": "usr/share/swss/buffer_headroom_mellanox.lua",
        "mode": 420,
        "source": "cfgmgr/buffer_headroom_mellanox.lua"
    },
    {
        "install_path": "usr/share/swss/buffer_headroom_vs.lua",
        "mode": 420,
        "source": "cfgmgr/buffer_headroom_mellanox.lua"
    },
    {
        "install_path": "usr/share/swss/buffer_pool_barefoot.lua",
        "mode": 420,
        "source": "cfgmgr/buffer_pool_barefoot.lua"
    },
    {
        "install_path": "usr/share/swss/buffer_pool_mellanox.lua",
        "mode": 420,
        "source": "cfgmgr/buffer_pool_mellanox.lua"
    },
    {
        "install_path": "usr/share/swss/buffer_pool_vs.lua",
        "mode": 420,
        "source": "cfgmgr/buffer_pool_mellanox.lua"
    },
    {
        "install_path": "usr/share/swss/drop_monitor.lua",
        "mode": 420,
        "source": "orchagent/drop_monitor.lua"
    },
    {
        "install_path": "usr/share/swss/eliminate_events.lua",
        "mode": 420,
        "source": "orchagent/eliminate_events.lua"
    },
    {
        "install_path": "usr/share/swss/lagids.lua",
        "mode": 420,
        "source": "orchagent/lagids.lua"
    },
    {
        "install_path": "usr/share/swss/nvda_port_trim_drop.lua",
        "mode": 420,
        "source": "orchagent/nvda_port_trim_drop.lua"
    },
    {
        "install_path": "usr/share/swss/pfc_detect_barefoot.lua",
        "mode": 420,
        "source": "orchagent/pfc_detect_barefoot.lua"
    },
    {
        "install_path": "usr/share/swss/pfc_detect_broadcom.lua",
        "mode": 420,
        "source": "orchagent/pfc_detect_broadcom.lua"
    },
    {
        "install_path": "usr/share/swss/pfc_detect_cisco-8000.lua",
        "mode": 420,
        "source": "orchagent/pfc_detect_cisco-8000.lua"
    },
    {
        "install_path": "usr/share/swss/pfc_detect_clounix.lua",
        "mode": 420,
        "source": "orchagent/pfc_detect_clounix.lua"
    },
    {
        "install_path": "usr/share/swss/pfc_detect_marvell-prestera.lua",
        "mode": 420,
        "source": "orchagent/pfc_detect_marvell-prestera.lua"
    },
    {
        "install_path": "usr/share/swss/pfc_detect_marvell-teralynx.lua",
        "mode": 420,
        "source": "orchagent/pfc_detect_marvell-teralynx.lua"
    },
    {
        "install_path": "usr/share/swss/pfc_detect_mellanox.lua",
        "mode": 420,
        "source": "orchagent/pfc_detect_mellanox.lua"
    },
    {
        "install_path": "usr/share/swss/pfc_detect_nephos.lua",
        "mode": 420,
        "source": "orchagent/pfc_detect_nephos.lua"
    },
    {
        "install_path": "usr/share/swss/pfc_detect_vs.lua",
        "mode": 420,
        "source": "orchagent/pfc_detect_vs.lua"
    },
    {
        "install_path": "usr/share/swss/pfc_restore.lua",
        "mode": 420,
        "source": "orchagent/pfc_restore.lua"
    },
    {
        "install_path": "usr/share/swss/pfc_restore_cisco-8000.lua",
        "mode": 420,
        "source": "orchagent/pfc_restore_cisco-8000.lua"
    },
    {
        "install_path": "usr/share/swss/port_flr.lua",
        "mode": 420,
        "source": "orchagent/port_flr.lua"
    },
    {
        "install_path": "usr/share/swss/port_rates.lua",
        "mode": 420,
        "source": "orchagent/port_rates.lua"
    },
    {
        "install_path": "usr/share/swss/rif_rates.lua",
        "mode": 420,
        "source": "orchagent/rif_rates.lua"
    },
    {
        "install_path": "usr/share/swss/trap_rates.lua",
        "mode": 420,
        "source": "orchagent/trap_rates.lua"
    },
    {
        "install_path": "usr/share/swss/tunnel_rates.lua",
        "mode": 420,
        "source": "orchagent/tunnel_rates.lua"
    },
    {
        "install_path": "usr/share/swss/watermark_bufferpool.lua",
        "mode": 420,
        "source": "orchagent/watermark_bufferpool.lua"
    },
    {
        "install_path": "usr/share/swss/watermark_pg.lua",
        "mode": 420,
        "source": "orchagent/watermark_pg.lua"
    },
    {
        "install_path": "usr/share/swss/watermark_queue.lua",
        "mode": 420,
        "source": "orchagent/watermark_queue.lua"
    }
]
