load("//bazel:production_sources.bzl", "SWSS_PROGRAMS")
load("//tools/bazel:cc.bzl", "swss_cc_binary", "swss_headers")
load("//tools/bazel:deps.bzl", "TEAM_DEPS")

package(default_visibility = ["//visibility:public"])

exports_files(glob([
    "*.cpp",
    "*.h",
]))

swss_headers(
    name = "headers",
    hdrs = glob(["*.h"]),
    includes = ["."],
)

swss_cc_binary(
    name = "teamsyncd",
    srcs = SWSS_PROGRAMS["teamsyncd"]["sources"],
    deps = TEAM_DEPS + [
        ":production_headers",
        "//lib:production_headers",
    ],
)
