#!/usr/bin/env python3
"""Run the pinned shared Rust metadata preparation before Bazel resolution."""

import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import sys
import tempfile
import urllib.request


# This bootstrap pin is separate from the Bazel module version: preparation runs
# before Bazel can resolve the module graph. Keep the source and hash together.
PREPARATION_REVISION = "52053f780f0f7d0348a7af5606f1dfcce93f2380"
PREPARATION_SHA256 = "38570821a60256a5d7a0c697e473aac49ff93af07aee3e1e63e2dc9528ffbb70"
PREPARATION_URL = (
    "https://raw.githubusercontent.com/securely1g/sonic-build-infra/"
    f"{PREPARATION_REVISION}/tools/rust/prepare.py"
)
RC_MARKER = "# Generated by sonic-build-infra tools/rust/prepare.py; do not edit.\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__, add_help=False)
    parser.add_argument("--prepared-common", type=Path)
    args, forwarded = parser.parse_known_args()
    workspace = Path(__file__).resolve().parents[2]
    # Invalidate the old Common selection before bootstrap download can fail.
    # Otherwise an updated MODULE pin could still use a previous local override.
    overrides = workspace / ".bazelrc.rust"
    if overrides.is_symlink():
        raise SystemExit("The generated overrides file must not be a symlink")
    if overrides.exists():
        if not overrides.read_text().startswith(RC_MARKER):
            raise SystemExit("Refusing to replace a non-generated overrides file")
        overrides.unlink()
    preparation = ["--overrides-rc", str(workspace / ".bazelrc.rust")]
    if args.prepared_common:
        # Image preparation has already verified this checkout and generated its
        # metadata. The image caller keeps the same Common module override.
        prepared = args.prepared_common.resolve()
        metadata = json.loads((prepared / "Cargo.Bazel.lock").read_text())
        if not metadata.get("crates"):
            raise SystemExit("Prepare Common's Rust metadata first")
        preparation.append(f"--bazel-arg=--override_module=sonic-swss-common={prepared}")
    else:
        preparation.extend([
            "--dependency=sonic-swss-common=sonic_swss_common",
            "--staging-dir", str(workspace / ".cargo-bazel-prep"),
        ])
    with urllib.request.urlopen(PREPARATION_URL, timeout=60) as response:
        source = response.read()
    if hashlib.sha256(source).hexdigest() != PREPARATION_SHA256:
        raise SystemExit("Shared Rust preparation checksum mismatch")
    with tempfile.TemporaryDirectory(prefix="sonic-rust-preparation-") as temporary:
        helper = Path(temporary) / "prepare.py"
        helper.write_bytes(source)
        return subprocess.call([
            sys.executable,
            str(helper),
            "--workspace", str(workspace),
            "--repository", "crates",
            *preparation, *forwarded,
        ])


if __name__ == "__main__":
    sys.exit(main())
