#!/usr/bin/env python3
"""Run the pinned shared Rust metadata preparation before Bazel resolution."""

import argparse
import hashlib
from pathlib import Path
import subprocess
import sys
import tempfile
import urllib.request


# This bootstrap pin is separate from the Bazel module version: preparation runs
# before Bazel can resolve the module graph. Keep the source and hash together.
PREPARATION_REVISION = "c13b2a8a7b9250c3e5c0da0d5d9c35d40f084bcb"
PREPARATION_SHA256 = "5847dcbc6a4098a8671c6802a490160097cf22f2bc306da329c7ae1d73334777"
PREPARATION_URL = (
    "https://raw.githubusercontent.com/securely1g/sonic-build-infra/"
    f"{PREPARATION_REVISION}/tools/rust/prepare.py"
)
RC_MARKER = "# Generated by sonic-build-infra tools/rust/prepare.py; do not edit.\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__, add_help=False)
    parser.add_argument("--prepared-common", type=Path)
    parser.add_argument("--overrides-rc", type=Path)
    args, forwarded = parser.parse_known_args()
    workspace = Path(__file__).resolve().parents[2]
    # Invalidate the old shared graph selection before bootstrap download can fail.
    # Otherwise an updated MODULE pin could still use a previous local override.
    overrides = args.overrides_rc or workspace / ".bazelrc.rust"
    # An image caller's rc does not replace SWSS's own try-import during source
    # resolution. Clear both generated files so a previous local pin cannot win.
    old_overrides = list(dict.fromkeys((workspace / ".bazelrc.rust", overrides)))
    for path in old_overrides:
        if path.is_symlink():
            raise SystemExit("The generated overrides file must not be a symlink")
        if path.exists() and not path.read_text().startswith(RC_MARKER):
            raise SystemExit("Refusing to replace a non-generated overrides file")
    for path in old_overrides:
        path.unlink(missing_ok=True)
    preparation = [
        "--shared-dependency=sonic-rust-deps=sonic_rust_deps",
        "--staging-dir", str(workspace / ".cargo-bazel-prep"),
        "--overrides-rc", str(overrides),
    ]
    if args.prepared_common:
        # External image builds supply their verified Common checkout. The
        # shared helper checks its Cargo inputs against the same dependency set.
        prepared = args.prepared_common.resolve()
        preparation.extend([
            f"--bazel-arg=--override_module=sonic-swss-common={prepared}",
            "--consumer-workspace", str(prepared),
        ])
    else:
        preparation.append("--dependency=sonic-swss-common=sonic_swss_common")
    with urllib.request.urlopen(PREPARATION_URL, timeout=60) as response:
        source = response.read()
    if hashlib.sha256(source).hexdigest() != PREPARATION_SHA256:
        raise SystemExit("Shared Rust preparation checksum mismatch")
    with tempfile.TemporaryDirectory(prefix="sonic-rust-preparation-") as temporary:
        helper = Path(temporary) / "prepare.py"
        helper.write_bytes(source)
        return subprocess.call([
            sys.executable,
            str(helper),
            "--workspace", str(workspace),
            *preparation, *forwarded,
        ])


if __name__ == "__main__":
    sys.exit(main())
