"""Prevent failed preparation from keeping obsolete Rust overrides active."""

from contextlib import ExitStack
import importlib.util
import io
from pathlib import Path
import tempfile
import unittest
from unittest.mock import patch
from urllib.error import URLError


ROOT = Path(__file__).resolve().parents[2]
SPEC = importlib.util.spec_from_file_location(
    "swss_prepare_rust", ROOT / "tools/bazel/prepare_rust.py"
)
PREPARATION = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(PREPARATION)

OWNED_OVERRIDE = (
    "# Generated by sonic-build-infra tools/rust/prepare.py; do not edit.\n"
    "common --override_module=sonic-swss-common=/previous/prepared/common\n"
)


class PreparationBootstrapTest(unittest.TestCase):
    def setUp(self):
        self.stack = ExitStack()
        self.addCleanup(self.stack.close)
        self.workspace = Path(self.stack.enter_context(tempfile.TemporaryDirectory()))
        self.override = self.workspace / ".bazelrc.rust"
        self.stack.enter_context(patch.object(
            PREPARATION, "__file__", str(self.workspace / "tools/bazel/prepare_rust.py")
        ))
        self.stack.enter_context(patch.object(
            PREPARATION.sys, "argv",
            ["prepare_rust.py", "--receipt", str(self.workspace / "preparation.json")],
        ))
        self.stack.enter_context(patch("sys.stderr", new_callable=io.StringIO))
        self.download = self.stack.enter_context(patch.object(
            PREPARATION.urllib.request, "urlopen"
        ))
        self.execute = self.stack.enter_context(patch.object(
            PREPARATION.subprocess, "call"
        ))

    def test_download_failure_removes_previous_owned_override(self):
        self.override.write_text(OWNED_OVERRIDE)
        self.download.side_effect = URLError("helper download unavailable")

        with self.assertRaises(URLError):
            PREPARATION.main()

        self.assertFalse(self.override.exists())
        self.execute.assert_not_called()

    def test_checksum_failure_removes_previous_owned_override(self):
        self.override.write_text(OWNED_OVERRIDE)
        self.download.return_value = io.BytesIO(b"unexpected helper contents")

        with self.assertRaisesRegex(SystemExit, "checksum mismatch"):
            PREPARATION.main()

        self.assertFalse(self.override.exists())
        self.execute.assert_not_called()

    def test_download_failure_removes_external_callers_owned_override(self):
        self.override.write_text(OWNED_OVERRIDE)
        external = self.workspace / "image.bazelrc.rust"
        external.write_text(OWNED_OVERRIDE)
        self.download.side_effect = URLError("helper download unavailable")
        with patch.object(PREPARATION.sys, "argv", [
            "prepare_rust.py", "--overrides-rc", str(external),
        ]):
            with self.assertRaises(URLError):
                PREPARATION.main()
        self.assertFalse(external.exists())
        self.assertFalse(self.override.exists())
        self.execute.assert_not_called()

    def test_user_written_override_is_preserved(self):
        contents = "common --override_module=sonic-swss-common=/my/local/common\n"
        self.override.write_text(contents)

        with self.assertRaises(SystemExit):
            PREPARATION.main()

        self.assertEqual(self.override.read_text(), contents)
        self.download.assert_not_called()
        self.execute.assert_not_called()

    def test_override_symlink_and_its_target_are_preserved(self):
        target = self.workspace / "user-settings.bazelrc"
        target.write_text(OWNED_OVERRIDE)
        self.override.symlink_to(target)

        with self.assertRaises(SystemExit):
            PREPARATION.main()

        self.assertTrue(self.override.is_symlink())
        self.assertEqual(target.read_text(), OWNED_OVERRIDE)
        self.download.assert_not_called()
        self.execute.assert_not_called()


if __name__ == "__main__":
    unittest.main()
