load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_python//python:defs.bzl", "py_binary")
load("@rules_rust_bindgen//:defs.bzl", "rust_bindgen")
load(":bindings.bzl", "bindings_directory")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "swss_common_c_api",
    hdrs = ["swss_common_c_api.h"],
    deps = ["@sonic_swss_common//:libswsscommon_shared"],
)

rust_bindgen(
    name = "swss_common_bindgen",
    bindgen_flags = ["--with-derive-partialeq"],
    cc_lib = ":swss_common_c_api",
    header = "swss_common_c_api.h",
    merge_cc_lib_objects_into_rlib = False,
)

bindings_directory(
    name = "swss_common_bindings_dir",
    src = ":swss_common_bindgen.rs",
)

py_binary(
    name = "stage_bindings",
    srcs = ["stage_bindings.py"],
    main = "stage_bindings.py",
    visibility = ["//visibility:private"],
)
