load("//bazel:production_sources.bzl", "SWSS_PROGRAMS")
load("//tools/bazel:cc.bzl", "swss_cc_binary", "swss_cc_library")
load("//tools/bazel:deps.bzl", "SWSS_DEPS")

package(default_visibility = ["//visibility:public"])

exports_files(glob([
    "*.cpp",
    "*.h",
]))

swss_cc_library(
    name = "headers",
    hdrs = glob(["*.h"]),
    asan = False,
    includes = ["."],
)

swss_cc_binary(
    name = "portsyncd",
    srcs = SWSS_PROGRAMS["portsyncd"]["sources"],
    deps = SWSS_DEPS + [
        ":headers",
        "//cfgmgr:headers",
        "//lib:headers",
    ],
)
